@extends('layouts.app')
@section('content')
<div class="mb-4"><h3>{{ $title }}</h3><div class="text-secondary">{{ ucfirst($module) }} · Mini ERP</div></div>
@if($module==='pos')
<div class="card shadow-sm"><div class="card-header fw-semibold">Transaksi Penjualan Retail</div><div class="card-body"><form method="POST" action="{{ route('erp.pos.store') }}" class="row g-3">@csrf<div class="col-md-5"><label class="form-label">Produk</label><select name="product_id" class="form-select" required><option value="">Pilih produk</option>@foreach($products as $p)<option value="{{ $p->id }}">{{ $p->name }} — Rp {{ number_format($p->selling_price,2,',','.') }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Qty</label><input name="qty" type="number" min="0.001" step="0.001" class="form-control" required></div><div class="col-md-3"><label class="form-label">Pembayaran</label><select name="payment_method" class="form-select"><option>Tunai</option><option>Transfer</option><option>QRIS</option></select></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100">Bayar</button></div></form></div></div>
@elseif($module==='purchases')
<div class="card shadow-sm"><div class="card-header fw-semibold">Pembelian + Penerimaan Stok</div><div class="card-body"><form method="POST" action="{{ route('erp.purchase.store') }}" class="row g-3">@csrf<div class="col-md-4"><label class="form-label">Produk</label><select name="product_id" class="form-select" required>@foreach($products as $p)<option value="{{ $p->id }}">{{ $p->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Gudang</label><select name="warehouse_id" class="form-select" required>@foreach($warehouses as $w)<option value="{{ $w->id }}">{{ $w->name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Qty</label><input name="qty" type="number" step="0.001" min="0.001" class="form-control" required></div><div class="col-md-2"><label class="form-label">Harga Beli</label><input name="unit_cost" type="number" step="0.01" min="0" class="form-control" required></div><div class="col-md-1 d-flex align-items-end"><button class="btn btn-primary">Simpan</button></div></form></div></div>
@elseif($module==='production')
<div class="card shadow-sm"><div class="card-header fw-semibold">Posting Produksi</div><div class="card-body"><form method="POST" action="{{ route('erp.production.store') }}" class="row g-3">@csrf<div class="col-md-4"><label class="form-label">BOM</label><select name="bom_id" class="form-select" required>@foreach(DB::table('boms')->where('is_active',1)->get() as $b)<option value="{{ $b->id }}">{{ $b->code }} — {{ $b->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Gudang</label><select name="warehouse_id" class="form-select" required>@foreach($warehouses as $w)<option value="{{ $w->id }}">{{ $w->name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Qty Produksi</label><input name="qty" type="number" step="0.001" min="0.001" class="form-control" required></div><div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100">Posting</button></div></form></div></div>
@elseif($module==='deliveries')
<div class="card shadow-sm"><div class="card-header fw-semibold">Buat Pengiriman</div><div class="card-body"><form method="POST" action="{{ route('erp.delivery.store') }}" class="row g-3">@csrf<div class="col-md-3"><label class="form-label">Kendaraan</label><select name="vehicle_id" class="form-select"><option value="">-</option>@foreach($vehicles as $v)<option value="{{ $v->id }}">{{ $v->code }} — {{ $v->plate_number }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Driver</label><select name="driver_id" class="form-select"><option value="">-</option>@foreach($drivers as $d)<option value="{{ $d->id }}">{{ $d->name }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Tujuan</label><input name="destination" class="form-control" required></div><div class="col-md-2"><label class="form-label">Jarak KM</label><input name="distance_km" type="number" step="0.01" class="form-control"></div><div class="col-12"><button class="btn btn-primary">Simpan Pengiriman</button></div></form></div></div>
@elseif($module==='journals')
<div class="card shadow-sm"><div class="card-header fw-semibold">Jurnal Umum</div><div class="card-body"><form method="POST" action="{{ route('erp.journal.store') }}" class="row g-3">@csrf<div class="col-md-4"><label class="form-label">Keterangan</label><input name="description" class="form-control" required></div><div class="col-md-3"><label class="form-label">Akun Debit</label><select name="debit_account" class="form-select" required>@foreach(DB::table('chart_of_accounts')->where('is_active',1)->get() as $a)<option value="{{ $a->id }}">{{ $a->code }} — {{ $a->name }}</option>@endforeach</select></div><div class="col-md-3"><label class="form-label">Akun Kredit</label><select name="credit_account" class="form-select" required>@foreach(DB::table('chart_of_accounts')->where('is_active',1)->get() as $a)<option value="{{ $a->id }}">{{ $a->code }} — {{ $a->name }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Jumlah</label><input name="amount" type="number" step="0.01" min="0.01" class="form-control" required></div><div class="col-12"><button class="btn btn-primary">Posting Jurnal</button></div></form></div></div>
@elseif($module==='stock')
<div class="card shadow-sm"><div class="card-header">Posisi Stok</div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Gudang</th><th>Produk</th><th>Qty</th><th>HPP Rata-rata</th></tr></thead><tbody>@forelse($rows as $r)<tr><td>{{ DB::table('warehouses')->find($r->warehouse_id)->name ?? '-' }}</td><td>{{ DB::table('products')->find($r->product_id)->name ?? '-' }}</td><td>{{ $r->qty }}</td><td>Rp {{ number_format($r->avg_cost,2,',','.') }}</td></tr>@empty<tr><td colspan="4" class="text-center py-4 text-secondary">Belum ada stok.</td></tr>@endforelse</tbody></table></div></div>
@else
<div class="card shadow-sm"><div class="card-header fw-semibold">{{ $title }}</div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>ID</th><th>Status / Data</th><th>Tanggal</th></tr></thead><tbody>@forelse($rows as $r)<tr><td>{{ $r->id }}</td><td><span class="badge text-bg-secondary">{{ $r->status ?? 'data' }}</span> @if(isset($r->invoice_no)) {{ $r->invoice_no }} @elseif(isset($r->purchase_no)) {{ $r->purchase_no }} @elseif(isset($r->journal_no)) {{ $r->journal_no }} @elseif(isset($r->delivery_no)) {{ $r->delivery_no }} @endif</td><td>{{ $r->created_at ?? '-' }}</td></tr>@empty<tr><td colspan="3" class="text-center py-4 text-secondary">Belum ada data.</td></tr>@endforelse</tbody></table></div>@if(is_object($rows) && method_exists($rows,'links'))<div class="card-footer">{{ $rows->links() }}</div>@endif</div>
@endif
@endsection
