<div class="pos-screen" id="posScreen">
<div class="pos-topbar"><div><strong>MINI ERP POS</strong><div class="small text-secondary mt-1">Tanggal: <span id="posDate"></span> &nbsp; | &nbsp; Jam: <span id="posClock"></span> &nbsp; | &nbsp; Kasir: <strong class="text-light">{{ auth()->user()->name }}</strong></div></div><div><span class="badge text-bg-{{ $openShift ? "success" : "warning" }}">{{ $openShift ? "SHIFT AKTIF" : "SHIFT BELUM DIBUKA" }}</span></div></div>
<div class="pos-main">
<div class="pos-entry">
<form method="POST" action="{{ route('erp.pos.add') }}" id="posAddForm" autocomplete="off">
<div class="row g-2 align-items-end">
<div class="col-md-5"><label class="form-label">Cari / Barcode</label><input id="posProductSearch" type="text" class="form-control form-control-lg" list="posProductList" placeholder="Ketik nama, SKU, barcode..." autofocus required><datalist id="posProductList"></datalist><input type="hidden" id="posProduct" name="product_id"></div>
<div class="col-md-2"><label class="form-label">Satuan</label><input id="posUnit" class="form-control form-control-lg" value="-" readonly></div>
<div class="col-md-2"><label class="form-label">Qty</label><input id="posQty" name="qty" type="number" min="0.001" step="0.001" class="form-control form-control-lg" value="1" required></div>
<div class="col-md-3"><button id="posAddButton" class="btn btn-primary btn-lg w-100" {{ !$openShift ? "disabled" : "" }}>+ TAMBAH BARANG</button></div>
</div><div id="posStockInfo" class="small text-secondary mt-1">Scan barcode atau cari barang.</div>
</form>
</div>
<div class="table-responsive pos-table-wrap"><table class="table table-hover align-middle mb-0"><thead><tr><th>Kode</th><th>Nama Barang</th><th class="text-end">Harga</th><th class="text-end">Qty</th><th>Satuan</th><th class="text-end">Diskon</th><th class="text-end">Sub Total</th></tr></thead><tbody id="posCartBody"><tr id="posEmpty"><td colspan="7" class="text-center text-secondary py-5">Belum ada barang.</td></tr></tbody></table></div>
<div class="pos-bottom">
<div class="pos-help"><strong>Shortcut:</strong> F2 = Edit barang &nbsp; | &nbsp; F4 = Fokus cari barang &nbsp; | &nbsp; F5 = Cetak terakhir &nbsp; | &nbsp; Esc = Tutup popup</div>
<div class="pos-summary"><div class="row g-2"><div class="col-sm-4"><label class="form-label">Diskon</label><input id="posDiscount" type="number" min="0" step="0.01" class="form-control text-end" value="{{ old('discount',0) }}"></div><div class="col-sm-4"><label class="form-label">Pembayaran</label><select id="posPaymentMethod" class="form-select"><option>Tunai</option><option>Transfer</option><option>QRIS</option></select></div><div class="col-sm-4"><label class="form-label">Nominal Bayar</label><input id="posPayment" type="number" min="0" step="0.01" class="form-control text-end" value="{{ $posTotal }}"></div></div>
<div class="d-flex justify-content-between mt-3"><span>SUBTOTAL</span><strong id="posSubtotalText">Rp {{ number_format($posSubtotal,0,',','.') }}</strong></div>
<div class="d-flex justify-content-between"><span>DISKON</span><strong id="posDiscountText">Rp 0</strong></div>
<div class="d-flex justify-content-between fs-3"><span>TOTAL</span><strong id="posTotal">Rp {{ number_format($posTotal,0,',','.') }}</strong></div>
<div class="d-flex justify-content-between mt-2"><span>KEMBALIAN</span><strong id="posChangeText">Rp 0</strong></div>
<div class="d-flex gap-2 mt-3"><button id="posClear" class="btn btn-outline-secondary flex-fill" {{ empty($posCart) ? "disabled" : "" }}>Kosongkan</button><button id="posPay" class="btn btn-success btn-lg flex-fill" {{ empty($posCart) ? "disabled" : "" }}>BAYAR & POSTING</button></div></div>
</div>
</div>
<div class="modal fade" id="posEditModal" tabindex="-1"><div class="modal-dialog modal-sm modal-dialog-centered"><div class="modal-content"><form id="posEditForm" method="POST"><div class="modal-header"><h5 class="modal-title">Edit Barang</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div id="posEditName" class="fw-semibold mb-3"></div><label class="form-label">Harga Transaksi</label><input id="posEditPrice" name="price" type="number" min="0" step="0.01" class="form-control mb-3" required><label class="form-label">Qty</label><input id="posEditQty" name="qty" type="number" min="0.001" step="0.001" class="form-control" required></div><div class="modal-footer justify-content-between"><button type="button" id="posEditDelete" class="btn btn-outline-danger">Hapus</button><button class="btn btn-primary">Simpan</button></div></form></div></div></div>
<div class="modal fade" id="posPrintModal" tabindex="-1"><div class="modal-dialog modal-sm modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Cetak Struk</h5></div><div class="modal-body text-center">Transaksi berhasil diposting.<br><strong id="posPrintInvoice"></strong><div class="mt-3">Cetak struk sekarang?</div></div><div class="modal-footer justify-content-center"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tidak</button><button type="button" class="btn btn-primary" id="posPrintYes">Ya, Cetak</button></div></div></div></div>
<script>
document.addEventListener('DOMContentLoaded',()=>{
const search=document.getElementById('posProductSearch'),product=document.getElementById('posProduct'),unit=document.getElementById('posUnit'),stock=document.getElementById('posStockInfo'),addForm=document.getElementById('posAddForm'),body=document.getElementById('posCartBody'),discount=document.getElementById('posDiscount'),payment=document.getElementById('posPayment'),method=document.getElementById('posPaymentMethod'),subtotalText=document.getElementById('posSubtotalText'),discountText=document.getElementById('posDiscountText'),totalText=document.getElementById('posTotal'),changeText=document.getElementById('posChangeText'),clearBtn=document.getElementById('posClear'),payBtn=document.getElementById('posPay');
const products=@json($products);
const dl=document.getElementById('posProductList');products.filter(p=>Number(p.stock_qty||p.stock||0)>0).forEach(p=>{let o=document.createElement('option');o.value=p.name;o.label=p.name+' — '+p.sku+(p.barcode?' · '+p.barcode:'');dl.appendChild(o);if(p.barcode){let b=document.createElement('option');b.value=p.barcode;b.label=p.name+' — '+p.barcode;dl.appendChild(b);}let s=document.createElement('option');s.value=p.sku;s.label=p.name+' — '+p.sku;dl.appendChild(s);});
const csrf=document.querySelector('meta[name="csrf-token"]')?.content||'{{ csrf_token() }}';let cart=@json(array_values($posCart));let currentKey=null,lastReceipt=null;
const money=n=>'Rp '+Math.round(n||0).toLocaleString('id-ID'),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function updateClock(){const d=new Date();document.getElementById('posDate').textContent=d.toLocaleDateString('id-ID',{day:'2-digit',month:'2-digit',year:'numeric'});document.getElementById('posClock').textContent=d.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false});}updateClock();setInterval(updateClock,1000);
function recalc(){let sub=cart.reduce((a,x)=>a+(+x.price||0)*(+x.qty||0),0),dis=Math.min(Math.max(+discount.value||0,0),sub),tot=sub-dis,paid=Math.max(+payment.value||0,0),change=Math.max(paid-tot,0);subtotalText.textContent=money(sub);discountText.textContent=money(dis);totalText.textContent=money(tot);changeText.textContent=money(method.value==='Tunai'?change:0);if(!payment.dataset.userEdited)payment.value=Math.round(tot);clearBtn.disabled=!cart.length;payBtn.disabled=!cart.length;return{sub,dis,tot,paid,change};}
function syncPaymentMode(){if(method.value!=='Tunai'){payment.value=Math.round(recalc().tot);payment.dataset.userEdited='';}recalc();}
function render(){if(!cart.length){body.innerHTML='<tr><td colspan="7" class="text-center text-secondary py-5">Belum ada barang.</td></tr>';recalc();return;}body.innerHTML=cart.map((x,i)=>'<tr class="pos-cart-row" data-key="'+i+'"><td>'+esc(x.code)+'</td><td>'+esc(x.name)+'</td><td class="text-end">'+money(x.price)+'</td><td class="text-end">'+Number(x.qty).toLocaleString('id-ID')+'</td><td>'+esc(x.selling_unit_code||'-')+'</td><td class="text-end">—</td><td class="text-end fw-semibold">'+money((+x.price||0)*(+x.qty||0))+'</td></tr>').join('');recalc();}
async function api(url,opts={}){opts.headers={...(opts.headers||{}),'X-CSRF-TOKEN':csrf,'Accept':'application/json','X-Requested-With':'XMLHttpRequest'};let r=await fetch(url,opts),j=await r.json();if(!r.ok)throw new Error(j.message||Object.values(j.errors||{}).flat()[0]||'Terjadi kesalahan.');return j;}
function selectProduct(){let v=(search.value||'').trim().toLowerCase(),x=products.find(p=>String(p.name).toLowerCase()===v||String(p.barcode||'').toLowerCase()===v||String(p.sku||'').toLowerCase()===v);if(!x){product.value='';unit.value='-';stock.textContent='Barang tidak ditemukan.';return false;}product.value=x.id;unit.value=x.selling_unit_code||x.unit||'-';stock.textContent='Stok tersedia: '+Number(x.stock_qty||x.stock||0).toLocaleString('id-ID')+' '+unit.value;return Number(x.stock_qty||x.stock||0)>0;}
addForm.addEventListener('submit',async e=>{e.preventDefault();if(!selectProduct())return;try{let j=await api(addForm.action,{method:'POST',body:new URLSearchParams({product_id:product.value,qty:document.getElementById('posQty').value})});cart=Object.values(j.cart||{});render();search.value='';product.value='';unit.value='-';stock.textContent='Scan barcode atau cari barang.';search.focus();}catch(e){alert(e.message);}});
body.addEventListener('click',event=>{let tr=event.target.closest('.pos-cart-row');if(!tr)return;currentKey=tr.dataset.key;let x=cart[currentKey];if(!x)return;document.getElementById('posEditName').textContent=x.code+' · '+x.name;document.getElementById('posEditPrice').value=x.price;document.getElementById('posEditQty').value=x.qty;document.getElementById('posEditForm').action='{{ url('/erp/pos/item') }}/'+x.product_id;new bootstrap.Modal(document.getElementById('posEditModal')).show();});
document.getElementById('posEditForm').addEventListener('submit',async e=>{e.preventDefault();let f=e.target;try{let j=await api(f.action,{method:'PUT',body:new URLSearchParams(new FormData(f))});cart=Object.values(j.cart||{});bootstrap.Modal.getInstance(document.getElementById('posEditModal')).hide();render();}catch(e){alert(e.message);}});
document.getElementById('posEditDelete').addEventListener('click',async()=>{if(!confirm('Hapus barang ini dari transaksi?'))return;let x=cart[currentKey];try{let j=await api('{{ url('/erp/pos/item') }}/'+x.product_id+'/remove',{method:'POST'});cart=Object.values(j.cart||{});bootstrap.Modal.getInstance(document.getElementById('posEditModal')).hide();render();}catch(e){alert(e.message);}});
discount.addEventListener('input',recalc);payment.addEventListener('input',()=>{payment.dataset.userEdited='1';recalc();});method.addEventListener('change',syncPaymentMode);
clearBtn.addEventListener('click',async()=>{if(!confirm('Kosongkan transaksi?'))return;try{await api('{{ route('erp.pos.clear') }}',{method:'POST'});cart=[];discount.value=0;payment.dataset.userEdited='';render();search.focus();}catch(e){alert(e.message);}});
payBtn.addEventListener('click',async()=>{if(!{{ $openShift ? 'true' : 'false' }}){alert('Shift kasir belum dibuka. Buka Shift Kasir terlebih dahulu.');return;}let z=recalc();if(z.paid<z.tot){alert('Nominal pembayaran kurang.');payment.focus();return;}if(method.value!=='Tunai'&&Math.round(z.paid*100)!==Math.round(z.tot*100)){alert('Transfer/QRIS harus dibayar tepat sesuai total.');payment.focus();return;}payBtn.disabled=true;try{let j=await api('{{ route('erp.pos.store') }}',{method:'POST',body:new URLSearchParams({payment_method:method.value,discount:z.dis,payment_amount:payment.value})});lastReceipt=j;document.getElementById('posPrintInvoice').textContent=j.invoice_no;cart=[];discount.value=0;payment.dataset.userEdited='';render();new bootstrap.Modal(document.getElementById('posPrintModal')).show();}catch(e){alert(e.message);payBtn.disabled=false;}});
document.getElementById('posPrintYes').addEventListener('click',()=>{printReceipt(lastReceipt);bootstrap.Modal.getInstance(document.getElementById('posPrintModal'))?.hide();});
function printReceipt(r){if(!r)return;let w=window.open('','_blank','width=420,height=700');if(!w){alert('Popup diblokir browser. Izinkan popup untuk mencetak.');return;}let rows=r.items.map(x=>{let qty=Number(x.qty).toLocaleString('id-ID');let price=Math.round(x.price).toLocaleString('id-ID');let line=Math.round((+x.price||0)*(+x.qty||0)).toLocaleString('id-ID');return '<tr><td colspan="2"><b>'+esc(x.name)+'</b></td></tr><tr><td>'+qty+' '+esc(x.selling_unit_code||'-')+' x '+price+'</td><td class="right">'+line+'</td></tr>';}).join('');
let entity=r.entity||{};let address=entity.address?'<div>'+esc(entity.address)+'</div>':'';let phone=entity.phone?'<div>Telp. '+esc(entity.phone)+'</div>':'';let discountRow=Number(r.discount||0)>0?'<div class="row"><span>Diskon</span><b>- '+money(r.discount)+'</b></div>':'';let html='<!doctype html><html><head><meta charset="utf-8"><title>'+esc(r.invoice_no)+'</title><style>@page{size:80mm auto;margin:0}*{box-sizing:border-box}html,body{margin:0;padding:0;width:80mm}body{font-family:Arial,sans-serif;font-size:11px;line-height:1.35;padding:4mm 4mm 6mm;color:#000}.center{text-align:center}.kop{font-weight:700;font-size:16px;margin-bottom:2px}.meta{margin-top:5px}.line{border-top:1px dashed #000;margin:6px 0}.row{display:flex;justify-content:space-between;gap:8px}.right{text-align:right}.items{width:100%;border-collapse:collapse}.items td{padding:1px 0;vertical-align:top}.items .right{white-space:nowrap}.grand{font-size:14px;margin-top:4px}.footer{margin-top:10px;text-align:center}.small{font-size:10px}@media print{body{padding-bottom:2mm}}</style></head><body><div class="center"><div class="kop">'+esc(entity.name||'MINI ERP')+'</div>'+address+phone+'<div class="small">TOKO BANGUNAN & PRODUKSI</div></div><div class="line"></div><div>No. Transaksi : '+esc(r.invoice_no)+'</div><div>Tanggal/Jam : '+esc(r.sale_date||'')+'</div><div>Kasir : '+esc(r.cashier||'')+'</div><div>Shift : '+esc(r.shift_id||'')+'</div><div>Customer : '+esc(r.customer||'Umum')+'</div><div class="line"></div><table class="items">'+rows+'</table><div class="line"></div><div class="row"><span>Subtotal</span><b>'+money(r.subtotal)+'</b></div>'+discountRow+'<div class="row grand"><span>TOTAL</span><b>'+money(r.total)+'</b></div><div class="line"></div><div class="row"><span>Pembayaran</span><b>'+esc(r.payment_method||'')+'</b></div><div class="row"><span>Dibayar</span><b>'+money(r.paid_amount)+'</b></div><div class="row"><span>Kembalian</span><b>'+money(r.change_amount)+'</b></div><div class="footer"><b>TERIMA KASIH</b><div>Selamat berbelanja</div><div class="small">Barang yang sudah dibeli tidak dapat dikembalikan tanpa bukti transaksi.</div><div class="line"></div><div class="small">Powered by MINI ERP</div></div><script>window.onload=function(){window.focus();window.print()}<\\/script></body></html>';w.document.open();w.document.write(html);w.document.close();}
document.addEventListener('keydown',e=>{if(e.key==='F2'){e.preventDefault();if(currentKey!==null)document.querySelector('.pos-cart-row[data-key="'+currentKey+'"]')?.click();}if(e.key==='F4'){e.preventDefault();search.focus();}if(e.key==='F5'){e.preventDefault();if(lastReceipt)printReceipt(lastReceipt);}});
search.addEventListener('input',selectProduct);search.addEventListener('change',selectProduct);search.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();addForm.requestSubmit();}});
recalc();
});
</script>
</div>