@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h3 class="mb-1">Harga Jual</h3><div class="text-secondary">Master harga jual item Retail</div></div></div>
<div class="modal fade" id="msgModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header" id="msgHeader"><h5 class="modal-title" id="msgTitle"></h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body" id="msgBody"></div><div class="modal-footer"><button class="btn btn-primary" data-bs-dismiss="modal">OK</button></div></div></div></div>
<div class="card shadow-sm"><div class="card-body border-bottom py-2"><div class="d-flex justify-content-between align-items-center"><div><div class="fw-semibold">Daftar Harga Jual</div><div class="small text-secondary">Perubahan harga tidak mengubah HPP atau stok.</div></div><button class="btn btn-outline-success btn-sm" id="export">Export Excel</button></div></div>
<div class="table-responsive"><table class="table table-sm table-hover align-middle mb-0" id="priceTable"><thead><tr><th>Kode</th><th>Item</th><th>Satuan</th><th class="text-end">Harga Jual</th><th class="text-center">Aksi</th></tr></thead><tbody>@foreach($rows as $r)<tr><td class="fw-semibold">{{$r->code}}</td><td>{{$r->name}}</td><td>{{$r->unit_code?:'-'}}</td><td class="text-end fw-semibold">Rp {{number_format((float)$r->selling_price,0,',','.')}}</td><td class="text-center"><button class="btn btn-outline-primary btn-sm edit" data-id="{{$r->id}}" data-name="{{$r->name}}" data-price="{{$r->selling_price}}">Edit</button> <button class="btn btn-outline-secondary btn-sm history" data-id="{{$r->id}}" data-name="{{$r->name}}">Histori</button></td></tr>@endforeach</tbody></table></div></div>
<div class="modal fade" id="editModal" tabindex="-1"><div class="modal-dialog modal-md modal-dialog-centered"><div class="modal-content"><form id="editForm"><div class="modal-header"><h5 class="modal-title">Edit Harga Jual</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" id="pid"><div class="mb-2"><label class="form-label">Item</label><input class="form-control" id="pname" readonly></div><div class="mb-2"><label class="form-label">Harga Jual *</label><input class="form-control" id="price" required></div><div class="mb-2"><label class="form-label">Markup % *</label><input class="form-control" id="markup" required></div><div class="mb-2"><label class="form-label">Tanggal Berlaku *</label><input type="date" class="form-control" id="date" value="{{now()->toDateString()}}" required></div><div><label class="form-label">Keterangan</label><input class="form-control" id="reason" maxlength="255"></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary" id="save">Simpan</button></div></form></div></div></div>
<div class="modal fade" id="historyModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Histori Harga Jual</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="small text-secondary mb-2" id="historyName"></div><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Tanggal</th><th class="text-end">Harga Lama</th><th class="text-end">Harga Baru</th><th class="text-end">Markup Lama</th><th class="text-end">Markup Baru</th><th>User</th><th>Keterangan</th></tr></thead><tbody id="historyBody"></tbody></table></div></div></div></div></div>
@endsection
@push('scripts')
<script>
(()=>{const edit=bootstrap.Modal.getOrCreateInstance(document.getElementById('editModal')),hist=bootstrap.Modal.getOrCreateInstance(document.getElementById('historyModal')),msg=bootstrap.Modal.getOrCreateInstance(document.getElementById('msgModal'));new DataTable('#priceTable',{pageLength:15,lengthMenu:[10,15,25,50,100],order:[[1,'asc']],columnDefs:[{targets:3,className:'text-end'},{targets:4,orderable:false,searchable:false}]});const fmt=v=>new Intl.NumberFormat('id-ID',{maximumFractionDigits:0}).format(Number(String(v??'').replace(/[^0-9-]/g,''))||0),show=(t,m)=>{const c={success:['Berhasil','✓','bg-success text-white'],danger:['Gagal','✕','bg-danger text-white'],warning:['Peringatan','!','bg-warning text-dark']}[t];document.getElementById('msgHeader').className='modal-header '+c[2];document.getElementById('msgTitle').textContent=c[1]+' '+c[0];document.getElementById('msgBody').textContent=m;msg.show();};
document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>{pid.value=b.dataset.id;pname.value=b.dataset.name;price.value=fmt(b.dataset.price);markup.value='0';date.value='{{now()->toDateString()}}';reason.value='';edit.show();});
price.oninput=()=>price.value?fmt(price.value):'';markup.oninput=()=>markup.value=markup.value.replace(/[^0-9,.-]/g,'');
editForm.onsubmit=async e=>{e.preventDefault();save.disabled=true;try{const r=await fetch('{{url('/master/harga-jual')}}/'+pid.value+'/edit',{method:'PUT',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]')?.content,'Accept':'application/json','Content-Type':'application/json'},body:JSON.stringify({effective_date:date.value,markup_percent:Number(markup.value.replace(',','.'))||0,selling_price:Number(price.value.replace(/[^0-9-]/g,''))||0,reason:reason.value})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.message||'Gagal menyimpan harga jual.');edit.hide();show('success',j.message);const row=[...document.querySelectorAll('#priceTable tbody tr')].find(x=>x.querySelector('.edit')?.dataset.id===pid.value);if(row)row.querySelector('td:nth-child(4)').textContent='Rp '+fmt(price.value); }catch(e){show('danger',e.message)}finally{save.disabled=false}};
document.querySelectorAll('.history').forEach(b=>b.onclick=async()=>{historyName.textContent=b.dataset.name;historyBody.innerHTML='<tr><td colspan="7" class="text-center text-secondary">Memuat...</td></tr>';hist.show();try{const r=await fetch('{{url('/master/harga-jual')}}/'+b.dataset.id+'/history',{headers:{'Accept':'application/json'}}),j=await r.json();historyBody.innerHTML=j.data.length?j.data.map(x=>'<tr><td>'+x.effective_date+'</td><td class="text-end">'+(x.old_price==null?'-':'Rp '+fmt(x.old_price))+'</td><td class="text-end">Rp '+fmt(x.new_price)+'</td><td class="text-end">'+(x.old_markup_percent==null?'-':Number(x.old_markup_percent).toFixed(2)+'%')+'</td><td class="text-end">'+Number(x.new_markup_percent||0).toFixed(2)+'%</td><td>'+String(x.changed_by_name||'-')+'</td><td>'+String(x.reason||'-')+'</td></tr>').join(''):'<tr><td colspan="7" class="text-center text-secondary">Belum ada histori.</td></tr>'}catch(e){historyBody.innerHTML='<tr><td colspan="7" class="text-center text-danger">'+e.message+'</td></tr>'}});
export.onclick=()=>{const rows=[['Kode','Item','Satuan','Harga Jual'],...new DataTable('#priceTable').rows({search:'applied'}).data().toArray().map(r=>r.slice(0,4).map(x=>String(x).replace(/<[^>]*>/g,'')))];const blob=new Blob([rows.map(r=>r.join('\t')).join('\n')],{type:'text/tab-separated-values'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='harga-jual-'+new Date().toISOString().slice(0,10)+'.xls';a.click();URL.revokeObjectURL(a.href)};
})();
</script>
@endpush