@extends('layouts.app')
@section('content')
<div class="card shadow-sm mb-3">
 <div class="card-header d-flex justify-content-between align-items-center"><div><div class="fw-semibold">DETAIL STOK</div><div class="small text-secondary">{{ $stock->product_name }} — {{ $stock->warehouse_name }}</div></div><a href="{{route('inventori.stok')}}" class="btn btn-outline-secondary btn-sm">Kembali</a></div>
 <div class="card-body"><div class="row g-3"><div class="col-md-3"><small class="text-secondary">Kode Item</small><div class="fw-semibold">{{$stock->code ?: $stock->sku}}</div></div><div class="col-md-3"><small class="text-secondary">Satuan</small><div>{{$stock->unit_name ?: $stock->unit_code ?: '-'}}</div></div><div class="col-md-3"><small class="text-secondary">Saldo</small><div class="fw-semibold">{{number_format($stock->qty,3,',','.')}} {{$stock->unit_code}}</div></div><div class="col-md-3"><small class="text-secondary">HPP / Nilai</small><div>Rp {{number_format($stock->avg_cost,0,',','.')}} / Rp {{number_format($stock->stock_value,0,',','.')}}</div></div></div></div>
</div>
<div class="card shadow-sm"><div class="card-header fw-semibold">HISTORI MUTASI BARANG</div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Tanggal</th><th>Referensi</th><th>Jenis Mutasi</th><th class="text-end">Masuk</th><th class="text-end">Keluar</th><th class="text-end">Saldo</th><th class="text-end">HPP</th></tr></thead><tbody>
@forelse($history as $h)<tr><td>{{date('d/m/Y H:i',strtotime($h->date))}}</td><td>{{$h->reference}}</td><td>{{ucwords(str_replace('_',' ',$h->movement_type))}}</td><td class="text-end">{{ $h->in ? number_format($h->in,3,',','.') : '-' }}</td><td class="text-end">{{ $h->out ? number_format($h->out,3,',','.') : '-' }}</td><td class="text-end fw-semibold">{{number_format($h->balance,3,',','.')}}</td><td class="text-end">Rp {{number_format($h->unit_cost,0,',','.')}}</td></tr>
@empty<tr><td colspan="7" class="text-center text-secondary py-4">Belum ada histori mutasi.</td></tr>@endforelse</tbody></table></div></div>
@endsection
