@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="mb-1">Penjualan Baru</h4><div class="text-secondary small">Buat transaksi penjualan</div></div><a href="{{ route('inventori.penjualan') }}" class="btn btn-outline-secondary">← Kembali ke Penjualan</a></div>
<div class="card shadow-sm"><div class="card-body">
<div class="row g-3"><div class="col-md-6"><label class="form-label">Tanggal</label><input type="date" class="form-control" value="{{ now()->toDateString() }}" readonly></div><div class="col-md-6"><label class="form-label">Cari Customer</label><div class="input-group"><input id="customerSearch" class="form-control" placeholder="Cari customer..." readonly><button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#customerModal">🔍</button></div></div><div class="col-md-6"><label class="form-label">Nomor</label><input class="form-control" value="Otomatis" readonly></div><div class="col-md-6"><label class="form-label">Pilih Unit</label><select id="unitSelect" class="form-select"><option value="">Pilih Unit</option>@foreach($units as $u)<option value="{{ $u->id }}">{{ $u->name }}</option>@endforeach</select></div></div>
<hr class="my-4"><div class="d-flex justify-content-between align-items-center mb-2"><h6 class="mb-0">Detail Penjualan</h6><button type="button" class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#itemModal">+ Tambah Item</button></div><div class="input-group mb-3"><input class="form-control" placeholder="Cari barang, kode atau barcode..." readonly><button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#itemModal">🔍</button></div>
<div class="table-responsive"><table class="table align-middle"><thead class="table-light"><tr><th>Item</th><th>Satuan</th><th class="text-end">Qty</th><th class="text-end">Harga</th><th class="text-end">Subtotal</th><th></th></tr></thead><tbody id="detailBody"><tr><td colspan="6" class="text-center text-secondary py-4">Belum ada item.</td></tr></tbody></table></div>
<hr class="my-4"><div class="row g-4"><div class="col-md-6"><h6>Informasi Customer</h6><div class="small text-secondary">Customer</div><div id="customerInfo" class="fw-semibold mb-3">-</div><div class="small text-secondary">Piutang Sebelumnya</div><div class="fw-semibold mb-2">Rp 0</div><div class="alert alert-warning py-2 d-none" id="arrears">⚠ Ada tunggakan sebelumnya</div><label class="form-label">Memo</label><textarea class="form-control" rows="3" placeholder="Catatan transaksi..."></textarea></div>
<div class="col-md-6"><h6>Informasi Transaksi</h6><div class="d-flex justify-content-between py-1"><span>Subtotal</span><strong>Rp 0</strong></div><div class="d-flex justify-content-between align-items-center py-1"><span>Diskon</span><input class="form-control text-end" style="max-width:160px" value="0"></div><div class="d-flex justify-content-between border-top mt-2 pt-2 fs-5"><strong>TOTAL</strong><strong>Rp 0</strong></div><div class="mt-3"><label class="form-label">Cara Bayar</label><select id="paymentMethod" class="form-select"><option>Tunai</option><option>Kredit / Bon</option></select></div><div id="dueDate" class="mt-3 d-none"><label class="form-label">Jatuh Tempo</label><input type="date" class="form-control"></div></div></div>
</div><div class="card-footer d-flex justify-content-end gap-2"><a href="{{ route('inventori.penjualan') }}" class="btn btn-outline-secondary">Batal</a><button type="button" class="btn btn-primary" onclick="alert('UI Penjualan sudah siap. Logic simpan dikerjakan setelah UI disetujui.')">Simpan Penjualan</button></div></div>
<div class="modal fade" id="customerModal" tabindex="-1"><div class="modal-dialog modal-sm modal-dialog-centered"><div class="modal-content"><div class="modal-header py-2"><h6 class="modal-title">Cari Customer</h6><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body p-2"><input id="customerFilter" class="form-control form-control-sm mb-2" placeholder="Ketik nama..."><div class="list-group list-group-flush">@foreach($customers as $c)<button type="button" class="list-group-item list-group-item-action customer-choice" data-name="{{ $c->name }}">{{ $c->name }}</button>@endforeach</div></div></div></div></div>
<div class="modal fade" id="itemModal" tabindex="-1"><div class="modal-dialog modal-sm modal-dialog-centered"><div class="modal-content"><div class="modal-header py-2"><h6 class="modal-title">Cari Item</h6><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body p-2"><input id="itemFilter" class="form-control form-control-sm mb-2" placeholder="Ketik nama / kode..."><div class="list-group list-group-flush">@foreach($products as $p)<button type="button" class="list-group-item list-group-item-action item-choice" data-name="{{ $p->name }}" data-code="{{ $p->code ?? $p->sku }}" data-unit="{{ $p->selling_unit_code ?? '-' }}" data-price="{{ $p->selling_price ?? 0 }}">{{ $p->code ?? $p->sku }} — {{ $p->name }}</button>@endforeach</div></div></div></div></div>
@endsection
@push('scripts')
<script>
document.querySelectorAll('.customer-choice').forEach(b=>b.onclick=()=>{document.getElementById('customerSearch').value=b.dataset.name;document.getElementById('customerInfo').textContent=b.dataset.name;bootstrap.Modal.getInstance(document.getElementById('customerModal')).hide()});
document.getElementById('customerFilter').oninput=e=>{let q=e.target.value.toLowerCase();document.querySelectorAll('.customer-choice').forEach(b=>b.classList.toggle('d-none',!b.textContent.toLowerCase().includes(q)))};
document.getElementById('itemFilter').oninput=e=>{let q=e.target.value.toLowerCase();document.querySelectorAll('.item-choice').forEach(b=>b.classList.toggle('d-none',!b.textContent.toLowerCase().includes(q)))};
document.querySelectorAll('.item-choice').forEach(b=>b.onclick=()=>{document.getElementById('detailBody').innerHTML='<tr><td><b>'+b.dataset.code+'</b><div class="small text-secondary">'+b.dataset.name+'</div></td><td>'+b.dataset.unit+'</td><td class="text-end">1</td><td class="text-end">Rp '+Number(b.dataset.price).toLocaleString('id-ID')+'</td><td class="text-end">Rp '+Number(b.dataset.price).toLocaleString('id-ID')+'</td><td><button type="button" class="btn btn-sm btn-outline-danger" onclick="this.closest(\'tr\').remove()">×</button></td></tr>';bootstrap.Modal.getInstance(document.getElementById('itemModal')).hide()});
document.getElementById('paymentMethod').onchange=e=>document.getElementById('dueDate').classList.toggle('d-none',e.target.value!=='Kredit / Bon');
</script>
@endpush