@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="mb-1">Detail Penjualan</h4><div class="text-secondary small">{{ $sale->invoice_no }}</div></div><div class="d-flex gap-2"><button type="button" class="btn btn-outline-primary" onclick="window.print()">🖨 Cetak Penjualan</button><a href="{{ route('inventori.penjualan') }}" class="btn btn-outline-secondary">← Kembali</a></div></div>
<div class="card shadow-sm">
<div class="card-body">
<div class="row g-3"><div class="col-md-6"><label class="form-label">Tanggal</label><input class="form-control" value="{{ \Carbon\Carbon::parse($sale->sale_date)->format('d/m/Y H:i') }}" readonly></div><div class="col-md-6"><label class="form-label">Nomor</label><input class="form-control" value="{{ $sale->invoice_no }}" readonly></div><div class="col-md-6"><label class="form-label">Customer</label><input class="form-control" value="{{ $sale->customer_name ?? 'Umum' }}" readonly></div><div class="col-md-6"><label class="form-label">Unit</label><input class="form-control" value="{{ $sale->unit_name ?? "-" }}" readonly></div></div>
<hr class="my-4"><h6 class="mb-2">Detail Penjualan</h6><div class="table-responsive"><table class="table align-middle"><thead class="table-light"><tr><th>Item</th><th>Satuan</th><th class="text-end">Qty</th><th class="text-end">Harga</th><th class="text-end">Subtotal</th></tr></thead><tbody>@forelse($items as $i)<tr><td><b>{{ $i->code }}</b><div class="small text-secondary">{{ $i->name }}</div></td><td>{{ $i->unit_code ?? '-' }}</td><td class="text-end">{{ number_format((float)$i->qty,3,',','.') }}</td><td class="text-end">Rp {{ number_format((float)$i->unit_price,0,',','.') }}</td><td class="text-end">Rp {{ number_format((float)$i->total,0,',','.') }}</td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-4">Tidak ada detail item.</td></tr>@endforelse</tbody></table></div>
<hr class="my-4"><div class="row g-4"><div class="col-md-6"><h6>Informasi Customer</h6><div class="small text-secondary">Customer</div><div class="fw-semibold mb-3">{{ $sale->customer_name ?? 'Umum' }}</div><div class="small text-secondary">Piutang Sebelumnya</div><div class="fw-semibold">Rp 0</div></div><div class="col-md-6"><h6>Informasi Transaksi</h6><div class="d-flex justify-content-between py-1"><span>Subtotal</span><strong>Rp {{ number_format((float)$sale->subtotal,0,',','.') }}</strong></div><div class="d-flex justify-content-between py-1"><span>Diskon</span><strong>Rp {{ number_format((float)$sale->discount,0,',','.') }}</strong></div><div class="d-flex justify-content-between border-top mt-2 pt-2 fs-5"><strong>TOTAL</strong><strong>Rp {{ number_format((float)$sale->total,0,',','.') }}</strong></div><div class="mt-3"><label class="form-label">Cara Bayar</label><input class="form-control" value="{{ $payments->pluck('method')->unique()->implode(', ') ?: '-' }}" readonly></div></div></div>
</div></div>
@endsection
@push('styles')
<style>@media print{.btn,.d-flex.justify-content-between.align-items-center.mb-3{display:none!important}.card{box-shadow:none!important;border:0!important}}</style>
@endpush