<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        /*
         * Business Unit is different from units:
         * - units        = Satuan/UOM (Kg, Zak, Pcs, ...)
         * - business_units = Unit usaha/operasional (Retail, Produksi, Jasa)
         */
        Schema::create('business_units', function (Blueprint $t) {
            $t->id();
            $t->foreignId('entity_id')->constrained();
            $t->string('code');
            $t->string('name');
            $t->boolean('is_active')->default(true);
            $t->timestamps();

            $t->unique(['entity_id', 'code']);
        });

        /*
         * Replace the legacy product_units table.
         * The old table belongs to the previous Item/UOM design and is
         * intentionally discarded because this migration introduces the
         * business-unit relation with a clean structure.
         */
        Schema::dropIfExists('product_units');

        /*
         * One Item can be used by more than one business unit.
         */
        Schema::create('product_units', function (Blueprint $t) {
            $t->id();
            $t->foreignId('product_id')->constrained('products')->cascadeOnDelete();
            $t->foreignId('business_unit_id')->constrained('business_units')->cascadeOnDelete();
            $t->timestamps();

            $t->unique(['product_id', 'business_unit_id']);
        });

        /*
         * Optional alternate UOM conversion.
         * Example:
         *   base UOM = Kg
         *   Zak = 50 Kg
         */
        Schema::create('unit_conversions', function (Blueprint $t) {
            $t->id();
            $t->foreignId('product_id')->constrained('products')->cascadeOnDelete();
            $t->foreignId('unit_id')->constrained('units')->cascadeOnDelete();
            $t->decimal('conversion_factor', 18, 6);
            $t->timestamps();

            $t->unique(['product_id', 'unit_id']);
        });

        Schema::table('products', function (Blueprint $t) {
            $t->string('code')->nullable()->after('entity_id');
            $t->string('item_type')->nullable()->after('name');
            $t->foreignId('base_unit_id')
                ->nullable()
                ->after('unit_id')
                ->constrained('units')
                ->nullOnDelete();
            $t->boolean('manage_stock')->default(true)->after('minimum_stock');

            $t->index(['entity_id', 'code']);
            $t->index(['entity_id', 'item_type']);
        });

        /*
         * Preserve existing data:
         * - code         <- legacy sku
         * - base_unit_id <- legacy unit_id
         * - item_type    <- legacy product type, all mapped to Barang
         */
        DB::statement("
            UPDATE products
            SET code = sku
            WHERE sku IS NOT NULL
              AND sku <> ''
        ");

        DB::statement("
            UPDATE products
            SET code = CONCAT('BRG-', LPAD(id, 5, '0'))
            WHERE code IS NULL OR code = ''
        ");

        DB::statement("
            UPDATE products
            SET item_type = 'barang'
            WHERE type IN ('raw_material', 'merchandise', 'wip', 'finished_goods')
               OR item_type IS NULL
        ");

        DB::statement("
            UPDATE products
            SET base_unit_id = unit_id
            WHERE unit_id IS NOT NULL
              AND base_unit_id IS NULL
        ");

        /*
         * Keep legacy columns (sku/type/unit_id/cost_price/selling_price/category_id)
         * for compatibility during the transition.
         * They will be removed only after dependent modules are migrated.
         */

        /*
         * Seed the initial business units for every existing entity.
         * Codes are stable; IDs are generated by the database.
         */
        DB::table('entities')->orderBy('id')->get()->each(function ($entity): void {
            foreach ([
                ['code' => 'RET', 'name' => 'Retail'],
                ['code' => 'PROD', 'name' => 'Produksi'],
                ['code' => 'JASA', 'name' => 'Jasa'],
            ] as $unit) {
                DB::table('business_units')->updateOrInsert(
                    [
                        'entity_id' => $entity->id,
                        'code' => $unit['code'],
                    ],
                    [
                        'name' => $unit['name'],
                        'is_active' => true,
                        'updated_at' => now(),
                        'created_at' => now(),
                    ]
                );
            }
        });
    }

    public function down(): void
    {
        Schema::table('products', function (Blueprint $t) {
            $t->dropForeign(['base_unit_id']);
            $t->dropIndex(['entity_id', 'code']);
            $t->dropIndex(['entity_id', 'item_type']);
            $t->dropColumn([
                'code',
                'item_type',
                'base_unit_id',
                'manage_stock',
            ]);
        });

        Schema::dropIfExists('unit_conversions');
        Schema::dropIfExists('product_units');
        Schema::dropIfExists('business_units');
    }
};
