<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ErpExtraController extends Controller
{
    private function entityId(): int { return DB::table('entities')->first()->id; }

    public function shiftStore(Request $r){$d=$r->validate(['opening_cash'=>'required|numeric|min:0']);DB::table('cash_shifts')->insert(['entity_id'=>$this->entityId(),'user_id'=>auth()->id(),'opened_at'=>now(),'opening_cash'=>$d['opening_cash'],'status'=>'open','created_at'=>now(),'updated_at'=>now()]);return back()->with('success','Shift kasir dibuka.');}
    public function bomStore(Request $r){$d=$r->validate(['product_id'=>'required|integer','code'=>'required|string','name'=>'required|string','output_qty'=>'required|numeric|min:0.001','material_product_id'=>'required|integer','material_qty'=>'required|numeric|min:0.001']);$eid=$this->entityId();DB::transaction(function()use($d,$eid){$bom=DB::table('boms')->insertGetId(['entity_id'=>$eid,'product_id'=>$d['product_id'],'code'=>$d['code'],'name'=>$d['name'],'output_qty'=>$d['output_qty'],'is_active'=>1,'created_at'=>now(),'updated_at'=>now()]);DB::table('bom_items')->insert(['bom_id'=>$bom,'product_id'=>$d['material_product_id'],'qty'=>$d['material_qty'],'created_at'=>now(),'updated_at'=>now()]);});return back()->with('success','BOM berhasil disimpan.');}
    public function opnameStore(Request $r){$d=$r->validate(['warehouse_id'=>'required|integer','product_id'=>'required|integer','actual_qty'=>'required|numeric|min:0']);$eid=$this->entityId();DB::transaction(function()use($d,$eid){$s=DB::table('warehouses_stocks')->where(['warehouse_id'=>$d['warehouse_id'],'product_id'=>$d['product_id']])->first();$system=$s?(float)$s->qty:0;$diff=(float)$d['actual_qty']-$system;$id=DB::table('stock_opnames')->insertGetId(['entity_id'=>$eid,'warehouse_id'=>$d['warehouse_id'],'user_id'=>auth()->id(),'opname_date'=>today(),'opname_no'=>'OPN-'.now()->format('YmdHis').'-'.Str::upper(Str::random(3)),'status'=>'posted','created_at'=>now(),'updated_at'=>now()]);DB::table('stock_opname_items')->insert(['stock_opname_id'=>$id,'product_id'=>$d['product_id'],'system_qty'=>$system,'actual_qty'=>$d['actual_qty'],'difference'=>$diff,'created_at'=>now(),'updated_at'=>now()]);if($s)DB::table('warehouses_stocks')->where('id',$s->id)->update(['qty'=>$d['actual_qty'],'updated_at'=>now()]);else DB::table('warehouses_stocks')->insert(['entity_id'=>$eid,'warehouse_id'=>$d['warehouse_id'],'product_id'=>$d['product_id'],'qty'=>$d['actual_qty'],'avg_cost'=>0,'created_at'=>now(),'updated_at'=>now()]);if($diff!=0)DB::table('stock_movements')->insert(['entity_id'=>$eid,'warehouse_id'=>$d['warehouse_id'],'product_id'=>$d['product_id'],'movement_type'=>'opname_adjustment','qty'=>$diff,'unit_cost'=>$s->avg_cost??0,'reference_type'=>'stock_opname','reference_id'=>$id,'occurred_at'=>now(),'created_by'=>auth()->id(),'created_at'=>now(),'updated_at'=>now()]);});return back()->with('success','Stock opname diposting dan stok disesuaikan.');}
    public function operationStore(Request $r){$d=$r->validate(['vehicle_id'=>'required|integer','operation_date'=>'required|date','km_start'=>'required|integer|min:0','km_end'=>'required|integer|gte:km_start','fuel_cost'=>'nullable|numeric|min:0','other_cost'=>'nullable|numeric|min:0','notes'=>'nullable|string']);DB::table('vehicle_operations')->insert(array_merge($d,['entity_id'=>$this->entityId(),'fuel_cost'=>$d['fuel_cost']??0,'other_cost'=>$d['other_cost']??0,'created_at'=>now(),'updated_at'=>now()]));DB::table('vehicles')->where('id',$d['vehicle_id'])->update(['current_km'=>$d['km_end'],'updated_at'=>now()]);return back()->with('success','Operasional armada disimpan.');}
    public function fleetCostStore(Request $r){$d=$r->validate(['vehicle_id'=>'required|integer','cost_date'=>'required|date','cost_type'=>'required|string','amount'=>'required|numeric|min:0','description'=>'nullable|string']);DB::table('fleet_costs')->insert(array_merge($d,['entity_id'=>$this->entityId(),'created_at'=>now(),'updated_at'=>now()]));return back()->with('success','Biaya armada disimpan.');}
}
