@extends('layouts.app')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h3 class="mb-1">User</h3><div class="text-secondary">Pengguna pada Entitas</div></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#userModal" onclick="newUser()">+ User</button></div>
@if(session('success'))<div class="alert alert-success py-2">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger py-2"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="card shadow-sm"><div class="card-header fw-semibold">{{ auth()->user()->entity?->name ?? 'Entitas' }}</div><div class="table-responsive"><table class="table table-hover mb-0"><thead class="table-light"><tr><th>Nama</th><th>Email</th><th>Role</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>
@forelse($users as $u)
<tr><td>{{ $u->name }}</td><td>{{ $u->email }}</td><td><span class="badge text-bg-secondary">{{ ucfirst($u->role) }}</span></td><td><span class="badge {{ $u->is_active ? 'text-bg-success':'text-bg-secondary' }}">{{ $u->is_active ? 'Aktif':'Nonaktif' }}</span></td><td class="text-end"><button class="btn btn-outline-primary btn-sm" title="Edit" data-bs-toggle="modal" data-bs-target="#userModal" onclick='editUser(@json($u))'>✎</button> <form method="POST" action="{{ route('pengaturan.user.toggle',$u->id) }}" class="d-inline">@csrf @method('PATCH')<button class="btn btn-outline-secondary btn-sm" title="Aktif/Nonaktif">↔</button></form></td></tr>
@empty<tr><td colspan="5" class="text-center text-secondary py-4">Belum ada user.</td></tr>@endforelse
</tbody></table></div></div>

<div class="modal fade" id="userModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST" id="userForm">@csrf<div class="modal-header"><h5 class="modal-title" id="userModalTitle">Tambah User</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="mb-2"><label class="form-label">Nama</label><input name="name" id="uName" class="form-control" required></div><div class="mb-2"><label class="form-label">Email</label><input type="email" name="email" id="uEmail" class="form-control" required></div><div class="mb-2"><label class="form-label">Role</label><select name="role" id="uRole" class="form-select" required><option value="admin">Admin</option><option value="kasir">Kasir</option><option value="inventori">Inventori</option><option value="akuntansi">Akuntansi</option></select></div><div class="mb-2"><label class="form-label">Password <span id="passwordHint" class="text-secondary">(minimal 8 karakter)</span></label><input type="password" name="password" id="uPassword" class="form-control" minlength="8"><input type="password" name="password_confirmation" id="uPasswordConfirmation" class="form-control mt-2" minlength="8" placeholder="Ulangi password"></div></div><div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan</button></div></form></div></div></div>
@push('scripts')
<script>
function newUser(){document.getElementById('userForm').action='{{ route('pengaturan.user.store') }}';document.getElementById('userForm').querySelector('[name="_method"]')?.remove();document.getElementById('userModalTitle').textContent='Tambah User';document.getElementById('uName').value='';document.getElementById('uEmail').value='';document.getElementById('uRole').value='admin';document.getElementById('uPassword').required=true;document.getElementById('uPasswordConfirmation').required=true;}
function editUser(u){document.getElementById('userForm').action='/pengaturan/user/'+u.id;let f=document.getElementById('userForm');if(!f.querySelector('[name="_method"]')){let i=document.createElement('input');i.type='hidden';i.name='_method';f.appendChild(i);}f.querySelector('[name="_method"]').value='PUT';document.getElementById('userModalTitle').textContent='Edit User';document.getElementById('uName').value=u.name;document.getElementById('uEmail').value=u.email;document.getElementById('uRole').value=u.role;document.getElementById('uPassword').value='';document.getElementById('uPasswordConfirmation').value='';document.getElementById('uPassword').required=false;document.getElementById('uPasswordConfirmation').required=false;}
</script>
@endpush
@endsection
